package com.example.pangol1_android.core.config

/**
 * Language support for the application
 */
object Languages {
    val SUPPORTED = mapOf(
        "en" to "English",
        "fr" to "Français",
        "es" to "Español",
        "de" to "Deutsch",
        "it" to "Italiano",
        "pt" to "Português",
        "ru" to "Русский",
        "ja" to "日本語",
        "ar" to "العربية",
        "zh" to "中文"
    )
    
    fun getName(code: String): String = SUPPORTED[code] ?: code
    fun isSupported(code: String): Boolean = code in SUPPORTED
}

/**
 * Multi-language string resources (10 languages supported)
 */
object Strings {
    private val translations = mapOf(
        // English
        "en" to mapOf(
            "app_name" to "Pangol1 Android",
            "load_data" to "Load Data",
            "data_table" to "Data Table",
            "visualization" to "Visualization",
            "bar_chart" to "Bar Chart",
            "line_chart" to "Line Chart",
            "scatter_plot" to "Scatter Plot",
            "pie_chart" to "Pie Chart",
            "histogram" to "Histogram",
            "export" to "Export",
            "settings" to "Settings",
            "language" to "Language",
            "theme" to "Theme",
            "light" to "Light",
            "dark" to "Dark",
            "auto" to "Auto (System)",
            "loading" to "Loading...",
            "error" to "Error",
            "no_data" to "No data loaded",
            "enter_url" to "Enter CSV URL",
            "paste_csv" to "Paste CSV Data",
            "load_url" to "Load from URL",
            "demo_data" to "Demo Data",
            "demo_sales" to "Sales Demo",
            "demo_temperature" to "Temperature Demo",
            "demo_population" to "Population Demo",
            "demo_grades" to "Student Grades Demo",
            "demo_traffic" to "Website Traffic Demo",
            "export_csv" to "Export CSV",
            "export_svg" to "Export SVG",
            "success" to "Success",
            "exported_to" to "Exported to",
            "select_columns" to "Select Columns",
            "x_axis" to "X Axis",
            "y_axis" to "Y Axis",
            "generate_chart" to "Generate Chart",
            "pick_file" to "Pick File",
            "file_browser" to "File Browser",
            "cancel" to "Cancel",
            "load" to "Load",
            "rows" to "rows",
            "columns" to "columns"
        ),
        // French
        "fr" to mapOf(
            "app_name" to "Pangol1 Android",
            "load_data" to "Charger les données",
            "data_table" to "Tableau de données",
            "visualization" to "Visualisation",
            "bar_chart" to "Diagramme en barres",
            "line_chart" to "Graphique en ligne",
            "scatter_plot" to "Diagramme de dispersion",
            "pie_chart" to "Diagramme circulaire",
            "histogram" to "Histogramme",
            "export" to "Exporter",
            "settings" to "Paramètres",
            "language" to "Langue",
            "theme" to "Thème",
            "light" to "Clair",
            "dark" to "Sombre",
            "auto" to "Auto (Système)",
            "loading" to "Chargement...",
            "error" to "Erreur",
            "no_data" to "Aucune donnée chargée",
            "enter_url" to "Entrez l'URL CSV",
            "paste_csv" to "Coller les données CSV",
            "load_url" to "Charger depuis URL",
            "demo_data" to "Données de démonstration",
            "demo_sales" to "Ventes",
            "demo_temperature" to "Température",
            "demo_population" to "Population",
            "demo_grades" to "Notes d'étudiants",
            "demo_traffic" to "Trafic web",
            "export_csv" to "Exporter CSV",
            "export_svg" to "Exporter SVG",
            "success" to "Succès",
            "exported_to" to "Exporté vers",
            "select_columns" to "Sélectionner colonnes",
            "x_axis" to "Axe X",
            "y_axis" to "Axe Y",
            "generate_chart" to "Générer graphique",
            "pick_file" to "Sélectionner fichier",
            "file_browser" to "Navigateur fichiers",
            "cancel" to "Annuler",
            "load" to "Charger",
            "rows" to "lignes",
            "columns" to "colonnes"
        ),
        // Spanish
        "es" to mapOf(
            "app_name" to "Pangol1 Android",
            "load_data" to "Cargar datos",
            "data_table" to "Tabla de datos",
            "visualization" to "Visualización",
            "bar_chart" to "Gráfico de barras",
            "line_chart" to "Gráfico de línea",
            "scatter_plot" to "Gráfico de dispersión",
            "pie_chart" to "Gráfico circular",
            "histogram" to "Histograma",
            "export" to "Exportar",
            "settings" to "Configuración",
            "language" to "Idioma",
            "theme" to "Tema",
            "light" to "Claro",
            "dark" to "Oscuro",
            "auto" to "Auto (Sistema)",
            "loading" to "Cargando...",
            "error" to "Error",
            "no_data" to "No hay datos cargados",
            "enter_url" to "Ingrese URL CSV",
            "paste_csv" to "Pegar datos CSV",
            "load_url" to "Cargar desde URL",
            "demo_data" to "Datos de demostración",
            "demo_sales" to "Ventas",
            "demo_temperature" to "Temperatura",
            "demo_population" to "Población",
            "demo_grades" to "Calificaciones de estudiantes",
            "demo_traffic" to "Tráfico web",
            "export_csv" to "Exportar CSV",
            "export_svg" to "Exportar SVG",
            "success" to "Éxito",
            "exported_to" to "Exportado a",
            "select_columns" to "Seleccionar columnas",
            "x_axis" to "Eje X",
            "y_axis" to "Eje Y",
            "generate_chart" to "Generar gráfico",
            "pick_file" to "Seleccionar archivo",
            "file_browser" to "Navegador de archivos",
            "cancel" to "Cancelar",
            "load" to "Cargar",
            "rows" to "filas",
            "columns" to "columnas"
        ),
        // German
        "de" to mapOf(
            "app_name" to "Pangol1 Android",
            "load_data" to "Daten laden",
            "data_table" to "Datentabelle",
            "visualization" to "Visualisierung",
            "bar_chart" to "Balkendiagramm",
            "line_chart" to "Liniendiagramm",
            "scatter_plot" to "Streudiagramm",
            "pie_chart" to "Kreisdiagramm",
            "histogram" to "Histogramm",
            "export" to "Exportieren",
            "settings" to "Einstellungen",
            "language" to "Sprache",
            "theme" to "Thema",
            "light" to "Hell",
            "dark" to "Dunkel",
            "auto" to "Auto (System)",
            "loading" to "Wird geladen...",
            "error" to "Fehler",
            "no_data" to "Keine Daten geladen",
            "enter_url" to "CSV-URL eingeben",
            "paste_csv" to "CSV-Daten einfügen",
            "load_url" to "Von URL laden",
            "demo_data" to "Demodaten",
            "demo_sales" to "Verkäufe",
            "demo_temperature" to "Temperatur",
            "demo_population" to "Bevölkerung",
            "demo_grades" to "Schülernoten",
            "demo_traffic" to "Website-Verkehr",
            "export_csv" to "CSV exportieren",
            "export_svg" to "SVG exportieren",
            "success" to "Erfolg",
            "exported_to" to "Exportiert nach",
            "select_columns" to "Spalten auswählen",
            "x_axis" to "X-Achse",
            "y_axis" to "Y-Achse",
            "generate_chart" to "Diagramm generieren",
            "pick_file" to "Datei auswählen",
            "file_browser" to "Dateibrowser",
            "cancel" to "Abbrechen",
            "load" to "Laden",
            "rows" to "Zeilen",
            "columns" to "Spalten"
        ),
        // Italian
        "it" to mapOf(
            "app_name" to "Pangol1 Android",
            "load_data" to "Carica dati",
            "data_table" to "Tabella dati",
            "visualization" to "Visualizzazione",
            "bar_chart" to "Grafico a barre",
            "line_chart" to "Grafico a linee",
            "scatter_plot" to "Grafico a dispersione",
            "pie_chart" to "Grafico a torta",
            "histogram" to "Istogramma",
            "export" to "Esporta",
            "settings" to "Impostazioni",
            "language" to "Lingua",
            "theme" to "Tema",
            "light" to "Chiaro",
            "dark" to "Scuro",
            "auto" to "Auto (Sistema)",
            "loading" to "Caricamento...",
            "error" to "Errore",
            "no_data" to "Nessun dato caricato",
            "enter_url" to "Inserisci URL CSV",
            "paste_csv" to "Incolla dati CSV",
            "load_url" to "Carica da URL",
            "demo_data" to "Dati demo",
            "demo_sales" to "Vendite",
            "demo_temperature" to "Temperatura",
            "demo_population" to "Popolazione",
            "demo_grades" to "Voti degli studenti",
            "demo_traffic" to "Traffico web",
            "export_csv" to "Esporta CSV",
            "export_svg" to "Esporta SVG",
            "success" to "Successo",
            "exported_to" to "Esportato in",
            "select_columns" to "Seleziona colonne",
            "x_axis" to "Asse X",
            "y_axis" to "Asse Y",
            "generate_chart" to "Genera grafico",
            "pick_file" to "Seleziona file",
            "file_browser" to "Browser file",
            "cancel" to "Annulla",
            "load" to "Carica",
            "rows" to "righe",
            "columns" to "colonne"
        ),
        // Portuguese
        "pt" to mapOf(
            "app_name" to "Pangol1 Android",
            "load_data" to "Carregar dados",
            "data_table" to "Tabela de dados",
            "visualization" to "Visualização",
            "bar_chart" to "Gráfico de barras",
            "line_chart" to "Gráfico de linhas",
            "scatter_plot" to "Gráfico de dispersão",
            "pie_chart" to "Gráfico de pizza",
            "histogram" to "Histograma",
            "export" to "Exportar",
            "settings" to "Configurações",
            "language" to "Idioma",
            "theme" to "Tema",
            "light" to "Claro",
            "dark" to "Escuro",
            "auto" to "Auto (Sistema)",
            "loading" to "Carregando...",
            "error" to "Erro",
            "no_data" to "Nenhum dado carregado",
            "enter_url" to "Digite URL CSV",
            "paste_csv" to "Colar dados CSV",
            "load_url" to "Carregar de URL",
            "demo_data" to "Dados de demonstração",
            "demo_sales" to "Vendas",
            "demo_temperature" to "Temperatura",
            "demo_population" to "População",
            "demo_grades" to "Notas dos alunos",
            "demo_traffic" to "Tráfego da web",
            "export_csv" to "Exportar CSV",
            "export_svg" to "Exportar SVG",
            "success" to "Sucesso",
            "exported_to" to "Exportado para",
            "select_columns" to "Selecionar colunas",
            "x_axis" to "Eixo X",
            "y_axis" to "Eixo Y",
            "generate_chart" to "Gerar gráfico",
            "pick_file" to "Escolher arquivo",
            "file_browser" to "Navegador de arquivos",
            "cancel" to "Cancelar",
            "load" to "Carregar",
            "rows" to "linhas",
            "columns" to "colunas"
        ),
        // Russian
        "ru" to mapOf(
            "app_name" to "Pangol1 Android",
            "load_data" to "Загрузить данные",
            "data_table" to "Таблица данных",
            "visualization" to "Визуализация",
            "bar_chart" to "Столбчатая диаграмма",
            "line_chart" to "Линейный график",
            "scatter_plot" to "Точечная диаграмма",
            "pie_chart" to "Круговая диаграмма",
            "histogram" to "Гистограмма",
            "export" to "Экспорт",
            "settings" to "Настройки",
            "language" to "Язык",
            "theme" to "Тема",
            "light" to "Светлая",
            "dark" to "Тёмная",
            "auto" to "Авто (Система)",
            "loading" to "Загрузка...",
            "error" to "Ошибка",
            "no_data" to "Нет загруженных данных",
            "enter_url" to "Введите URL CSV",
            "paste_csv" to "Вставить данные CSV",
            "load_url" to "Загрузить с URL",
            "demo_data" to "Демо-данные",
            "demo_sales" to "Продажи",
            "demo_temperature" to "Температура",
            "demo_population" to "Население",
            "demo_grades" to "Оценки студентов",
            "demo_traffic" to "Трафик сайта",
            "export_csv" to "Экспорт CSV",
            "export_svg" to "Экспорт SVG",
            "success" to "Успех",
            "exported_to" to "Экспортировано в",
            "select_columns" to "Выберите колонки",
            "x_axis" to "Ось X",
            "y_axis" to "Ось Y",
            "generate_chart" to "Создать диаграмму",
            "pick_file" to "Выбрать файл",
            "file_browser" to "Обозреватель файлов",
            "cancel" to "Отмена",
            "load" to "Загрузить",
            "rows" to "строк",
            "columns" to "колонок"
        ),
        // Japanese
        "ja" to mapOf(
            "app_name" to "Pangol1 Android",
            "load_data" to "データを読み込む",
            "data_table" to "データテーブル",
            "visualization" to "ビジュアライゼーション",
            "bar_chart" to "棒グラフ",
            "line_chart" to "折れ線グラフ",
            "scatter_plot" to "散布図",
            "pie_chart" to "円グラフ",
            "histogram" to "ヒストグラム",
            "export" to "エクスポート",
            "settings" to "設定",
            "language" to "言語",
            "theme" to "テーマ",
            "light" to "ライト",
            "dark" to "ダーク",
            "auto" to "自動（システム）",
            "loading" to "読み込み中...",
            "error" to "エラー",
            "no_data" to "データが読み込まれていません",
            "enter_url" to "CSV URLを入力",
            "paste_csv" to "CSVデータを貼り付け",
            "load_url" to "URLから読み込む",
            "demo_data" to "デモデータ",
            "demo_sales" to "販売",
            "demo_temperature" to "温度",
            "demo_population" to "人口",
            "demo_grades" to "学生成績",
            "demo_traffic" to "ウェブトラフィック",
            "export_csv" to "CSVをエクスポート",
            "export_svg" to "SVGをエクスポート",
            "success" to "成功",
            "exported_to" to "にエクスポート",
            "select_columns" to "列を選択",
            "x_axis" to "X軸",
            "y_axis" to "Y軸",
            "generate_chart" to "グラフを生成",
            "pick_file" to "ファイルを選択",
            "file_browser" to "ファイルブラウザ",
            "cancel" to "キャンセル",
            "load" to "読み込む",
            "rows" to "行",
            "columns" to "列"
        ),
        // Arabic
        "ar" to mapOf(
            "app_name" to "Pangol1 Android",
            "load_data" to "تحميل البيانات",
            "data_table" to "جدول البيانات",
            "visualization" to "التصور",
            "bar_chart" to "رسم بياني عمودي",
            "line_chart" to "رسم بياني خطي",
            "scatter_plot" to "رسم تشتت",
            "pie_chart" to "رسم بياني دائري",
            "histogram" to "الرسم البياني",
            "export" to "تصدير",
            "settings" to "الإعدادات",
            "language" to "اللغة",
            "theme" to "المظهر",
            "light" to "فاتح",
            "dark" to "غامق",
            "auto" to "تلقائي (النظام)",
            "loading" to "جاري التحميل...",
            "error" to "خطأ",
            "no_data" to "لا توجد بيانات محملة",
            "enter_url" to "أدخل رابط CSV",
            "paste_csv" to "لصق بيانات CSV",
            "load_url" to "تحميل من الرابط",
            "demo_data" to "بيانات توضيحية",
            "demo_sales" to "المبيعات",
            "demo_temperature" to "درجة الحرارة",
            "demo_population" to "السكان",
            "demo_grades" to "درجات الطلاب",
            "demo_traffic" to "حركة المرور على الويب",
            "export_csv" to "تصدير CSV",
            "export_svg" to "تصدير SVG",
            "success" to "نجاح",
            "exported_to" to "تم التصدير إلى",
            "select_columns" to "اختر الأعمدة",
            "x_axis" to "المحور X",
            "y_axis" to "المحور Y",
            "generate_chart" to "إنشاء رسم بياني",
            "pick_file" to "اختر ملف",
            "file_browser" to "متصفح الملفات",
            "cancel" to "إلغاء",
            "load" to "تحميل",
            "rows" to "صفوف",
            "columns" to "أعمدة"
        ),
        // Chinese
        "zh" to mapOf(
            "app_name" to "Pangol1 Android",
            "load_data" to "加载数据",
            "data_table" to "数据表格",
            "visualization" to "可视化",
            "bar_chart" to "柱状图",
            "line_chart" to "折线图",
            "scatter_plot" to "散点图",
            "pie_chart" to "饼图",
            "histogram" to "直方图",
            "export" to "导出",
            "settings" to "设置",
            "language" to "语言",
            "theme" to "主题",
            "light" to "浅色",
            "dark" to "深色",
            "auto" to "自动（系统）",
            "loading" to "加载中...",
            "error" to "错误",
            "no_data" to "未加载任何数据",
            "enter_url" to "输入 CSV URL",
            "paste_csv" to "粘贴 CSV 数据",
            "load_url" to "从 URL 加载",
            "demo_data" to "演示数据",
            "demo_sales" to "销售",
            "demo_temperature" to "温度",
            "demo_population" to "人口",
            "demo_grades" to "学生成绩",
            "demo_traffic" to "网站流量",
            "export_csv" to "导出 CSV",
            "export_svg" to "导出 SVG",
            "success" to "成功",
            "exported_to" to "已导出到",
            "select_columns" to "选择列",
            "x_axis" to "X 轴",
            "y_axis" to "Y 轴",
            "generate_chart" to "生成图表",
            "pick_file" to "选择文件",
            "file_browser" to "文件浏览器",
            "cancel" to "取消",
            "load" to "加载",
            "rows" to "行",
            "columns" to "列"
        )
    )
    
    fun get(key: String, language: String = "en"): String {
        return translations[language]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
